# Generated by Django 4.0.8 on 2024-01-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_details',
            name='message',
            field=models.TextField(),
        ),
    ]
